### ISSUE TITLE
Vr Buttons error with not setup in udon

### ISSUE THREAD

**Issue by nosjo** [CyanLaser/CyanEmu#18]
Pretty much any vr button from this list https://docs.google.com/spreadsheets/d/1_iF0NjJniTnQn-knCjb5nLh6rlLfW_QKM19wtSW_S9w/edit

Exemple from my own code of error that halts udon
Input Button Oculus_CrossPlatform_Button4 is not setup.

Did look into code but not sure how input entirely works in unity

**Comment by CyanLaser** [comment]
All the "Oculus_CrossPlatform" axes have been implemented with 4f8cd5c2968f75b207e1fa1e043d7e5b57f71ffa
Do you believe the other axes should also be added?

**Comment by nosjo** [comment]
Not sure since i got for the crossplatform ones personaly but maybe since more control?

**Comment by orels1** [comment]
Based on discussions in prefabs and U# servers - most people seem to use Oculus_CrossPlatform + horizontal/vertical stuff

**Comment by CyanLaser** [comment]
While not all inputs have been added, I'm closing this as it covers the majority of cases. We can open a new issue if people really want the other input axes.
