### ISSUE TITLE
Support for multiple spawnpoints

### ISSUE THREAD

**Issue by JordoVR** [CyanLaser/CyanEmu#24]
Adding support for multiple spawnpoints and possibly the different spawn orders specified in the VRC descriptor.

**Comment by ModerateWinGuy** [comment]
If you could have a configuration option to just spawn the player at the current location of your scene view, so you could test whatever your looking at right after spawning, that would be fabulous!

**Comment by CyanLaser** [comment]
Multiple spawn point support was added in v0.3.6. Closing. Having the player spawn at the scene view location is unrelated to vrchat's spawn system.
