### ISSUE TITLE
Add a [SelectionBase] attribute to the CyanEmuPlayer class

### ISSUE THREAD

**Issue by rurre** [CyanLaser/CyanEmu#34]
Add a [SelectionBase] attribute to the CyanEmuPlayer class so that when you click on the player in Scene View it will select the player object and not the mesh object. It's really useful when you want to move the player around.

**Comment by CyanLaser** [comment]
Sounds like a good idea. I'll look into adding it for the next version.

**Comment by CyanLaser** [comment]
Added in fffc95dab416d3c6b0c76dacd9516f114f4f939d

**Comment by rurre** [comment]
Neat, thanks!
