### ISSUE TITLE
Udon input axis not resetting to zero

### ISSUE THREAD

**Issue by nosjo** [CyanLaser/CyanEmu#40]
so if you use exemply InputMoveHorizontal or InputMoveVertical the 3 values there can get from keyboard is -1, 0 and 1 but there newer get 0 so when you let go off the key it just continues with either -1 or 1

**Comment by daalta** [comment]
Yup, still an issue!

Here's what I would expect:
* Press W -> 1
* Release W -> 0
* Press S -> -1
* Release S -> 0

Here's what CyanEmu does:

* Press W -> 0
* Release W -> 1
* Press S -> 0
* Release S -> -1

**Comment by CyanLaser** [comment]
4006f8a2b00266442619161fdeab46e26080368b fixes the issue. Looks like the wrong variable was used.

**Comment by CyanLaser** [comment]
Resolved with v0.3.10
