### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by RiskiVR** [CyanLaser/CyanEmu#52]
Current requirements stated in README is "Unity 2018.4.20f1" which is very outdated.

**Comment by BlueSky-fur** [comment]
you could just make a PR tho ^^

**Comment by CyanLaser** [comment]
Resolved with #56

**Comment by RiskiVR** [comment]
> you could just make a PR tho ^^

I would if I knew how to do that lol

**Comment by BlueSky-fur** [comment]
> > you could just make a PR tho ^^
> 
> I would if I knew how to do that lol

I did it allready, but heres the how-to for next time!
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
