### ISSUE TITLE
Udon input unreliable and slow

### ISSUE THREAD

**Issue by nosjo** [CyanLaser/CyanEmu#54]
So allmost none of the input events are sent to udon but if i modify CyanEmuPlayerController "HandleUdonInput();" to be called in update instead of fixedupdate i can get around this issue and then all inputs are send to udon properly

**Comment by nosjo** [comment]
So made a pull request of the fix now since might be useful for others to #55

**Comment by CyanLaser** [comment]
This appears to be a duplicate or subset of #48
